from collections import defaultdict

names_dict = {
    "Quin Snyder": ["quin", "snyder"],
    "Joe Mazzulla": ["mazzulla", "mazula", "mazulla", " maz ", " mazz "],
    "Doc Rivers": ["rivers", " doc "],
    "Adrian Griffin": ["adrian", "griffin"],
    "Erik Spoelstra": ["erik", "spoelstra", " spo "],
    "Jacque Vaughn": ["jacque", "jaque", "vaughn", "vaugn"],
    "Steve Clifford": ["clifford"],
    "Billy Donovan": ["billy donovan", "billy"],
    "J.B. Bickerstaff": ["bickerstaff", "j.b"],
    "Jason Kidd": [" kidd ", "j kid", "jason"],
    "Michael Malone": ["malone"],
    "Monty Williams": ["monty"],
    "Chris Finch": ["finch"],
    "Steve Kerr": ["kerr"],
    "Ime Udoka": [" ime ", "udoka"],
    "Rick Carlisle": ["carlisle"],
    "Tyronn Lue": [" lue ", "tyronn"],
    "Darvin Ham": [" ham ", "darvin"],
    "Taylor Jenkins": ["jenkins"],
    "Willie Green": ["willie"],
    "Tom Thibodeau": ["thibodeau", "thibs", "tibs", "tibbs"],
    "Mark Daigneault": ["daigneault", "dagneault", "dagnault"],
    "Jamahl Mosley": ["jamahl", "mosley"],
    "Nick Nurse": ["nurse"],
    "Mike Budenholzer": ["budenholzer", " bud ", "budenholzer"],
    "Mike Brown": ["mike brown", "coach brown", "coach mike"],
    "Gregg Popovich": [" pop ", "popovich"],
    "Darko Rajakovic": ["darko", "rajakovic"],
    "Will Hardy": ["hardy"],
    "Wes Unseld Jr": [" wes ", "unseld"]
}
coaches = {"Quin Snyder", "Joe Mazzulla", "Doc Rivers", "Adrian Griffin",
           "Jacque Vaughn", "Steve Clifford", "Billy Donovan",
           "J.B. Bickerstaff", "Jason Kidd", "Michael Malone", "Monty Williams",
           "Chris Finch", "Steve Kerr", "Ime Udoka", "Rick Carlisle",
           "Tyronn Lue", "Darvin Ham", "Taylor Jenkins", "Erik Spoelstra",
           "Willie Green", "Tom Thibodeau", "Mark Daigneault", "Jamahl Mosley",
           "Nick Nurse", "Mike Budenholzer", "Chauncey Billups", "Mike Brown",
           "Gregg Popovich", "Darko Rajakovic", "Will Hardy", "Wes Unseld Jr."}

catch_coaches = {"quin", "snyder", "mazzulla", "mazula", "mazzula", "mazulla",
           " maz ", " mazz ", " doc ", "adrian", "griffin", " erik ",
           "jacque", "vaughn", "vaugn", "clifford", "donovan",
           "j.b", "bickerstaff", " kidd ", "malone", "monty", "williams",
           "finch", "kerr", " ime ", "udoka", "carlisle", "tyronn", "lue",
           "darvin", " ham ", "taylor", "jenkins", " spo ", "spoelstra",
           "rivers", "willie green", "thibodeau", "thibbs", "tibbs", " tibs ",
           "daigneault", "dagneault", "dagnault", "jamahl", "mosley",
           "nurse", "budenholzer", " bud ", "chauncey", "billups", "mike brown",
           "coach brown", "coach mike", "gregg", "popovich", " pop ", "darko",
           "rajakovic", "hardy", "wes", "unseld"}


